// D:\Projects\Kalwanga\packages\web\utils\index.ts

// ============================================
// FORMatters - Export everything from formatters
// ============================================
export {
  formatters,
  formatCurrency,
  formatDate,
  formatDateTime,
  formatTime,
  formatShortDate,
  formatISODate,
  formatRelativeTime,
  formatNumber,
  formatPercent,
  formatCompactNumber,
  formatOrdinal,
  truncateString,
  capitalizeString,
  capitalizeWords,
  toTitleCase,
  toSentenceCase,
  formatPhoneNumber,
  formatFileSize,
  formatDuration,
  formatUrlForDisplay,
  pluralize,
  formatList,
  formatDateRange,
  formatAddress,
  padZero,
  statusWithColor,
  paymentMethodWithIcon,
  // Sales-specific formatters
  formatReceiptNumber,
  formatInvoiceNumber,
  formatReturnNumber,
  formatRefundNumber,
  formatStatusLabel,
  formatPaymentMethodLabel,
  formatQuantity,
  formatDiscount,
  formatTax,
  formatSubtotal,
  formatChange,
  formatSaleSummary,
  formatTimeRange,
  formatPercentageChange,
} from './formatters';

// ============================================
// TOAST - Export from toast-manager
// ============================================
export {
  toast,
  useToast,
  ToastContainer,
  type Toast,
  type ToastOptions,
} from './toast-manager';

// ============================================
// VALIDATORS - Export from validators
// ============================================
export {
  validateEmail,
  validateEmailDetailed,
  validatePhone,
  validatePhoneDetailed,
  validateRequired,
  validateRequiredDetailed,
  validateMinLength,
  validateMinLengthDetailed,
  validateMaxLength,
  validateMaxLengthDetailed,
  validateNumber,
  validateNumberDetailed,
  validatePositiveNumber,
  validatePositiveNumberDetailed,
  validateNonNegativeNumber,
  validateNonNegativeNumberDetailed,
  validateZipCode,
  validateZipCodeDetailed,
  validateURL,
  validateURLDetailed,
  validatePassword,
  validatePasswordDetailed,
  validatePasswordMatch,
  validatePasswordMatchDetailed,
  validateSKU,
  validateSKUDetailed,
  validateBarcode,
  validateBarcodeDetailed,
  validateDate,
  validateDateDetailed,
  validateFutureDate,
  validateFutureDateDetailed,
  validatePastDate,
  validatePastDateDetailed,
  validateRange,
  validateRangeDetailed,
  validateArrayLength,
  validateArrayLengthDetailed,
  validateObject,
  validateObjectDetailed,
  validateBoolean,
  validateBooleanDetailed,
  validateCurrency,
  validateCurrencyDetailed,
  validatePercentage,
  validatePercentageDetailed,
  validateCreditCard,
  validateCreditCardDetailed,
  validateExpiryDate,
  validateExpiryDateDetailed,
  // Sales-specific validators
  validateReceiptNumber,
  validateReceiptNumberDetailed,
  validateInvoiceNumber,
  validateInvoiceNumberDetailed,
  validatePaymentAmount,
  validatePaymentAmountDetailed,
  validateDiscount,
  validateDiscountDetailed,
  validateQuantity,
  validateQuantityDetailed,
  validateTaxRate,
  validateTaxRateDetailed,
  validateReturnReason,
  validateReturnReasonDetailed,
  validateAgainstRules,
  createValidator,
  isEmpty,
  getFieldStatus,
  getFieldErrors,
  type ValidationResult,
  type ValidationRule,
  type ValidationSchema,
} from './validators';

// ============================================
// CONSTANTS - Export from constants
// ============================================
export {
  constants,
  APP_NAME,
  APP_VERSION,
  API_URL,
  TOKEN_KEY,
  USER_KEY,
  CURRENCY,
  CURRENCY_SYMBOL,
  DATE_FORMAT,
  TIME_FORMAT,
  DATE_TIME_FORMAT,
  PAGINATION,
  FILE_UPLOAD,
  USER_ROLES,
  ORDER_STATUSES,
  SALE_STATUSES,
  PAYMENT_METHODS,
  PAYMENT_STATUSES,
  INVENTORY_TRANSACTION_TYPES,
  RETURN_STATUSES,
  RETURN_TYPES,
  REFUND_STATUSES,
  REFUND_METHODS,
  INVOICE_STATUSES,
  INVOICE_PAYMENT_TERMS,
  RECEIPT_STATUSES,
  RECEIPT_TYPES,
  SHIFT_STATUSES,
  SHIFT_TYPES,
  CASH_REGISTER_STATUSES,
  CASH_TRANSACTION_TYPES,
  REPORT_TYPES,
  REPORT_FORMATS,
  REPORT_DATE_RANGES,
  EXPORT_FORMATS,
  EXPORT_TYPES,
  EXPORT_STATUSES,
  DATE_RANGES,
  GROUP_BY,
  NOTIFICATION_TYPES,
  NOTIFICATION_PRIORITIES,
  CURRENCIES,
  STATUS_COLORS,
  PAYMENT_METHOD_COLORS,
  STATUS_LABELS,
  PAYMENT_METHOD_LABELS,
  DATE_RANGES_LABELS,
  TAX_RATE,
  LOYALTY_POINTS_PER_DOLLAR,
  SALE_SETTINGS,
  // Helper functions from constants
  getStatusColor,
  getPaymentMethodColor,
  getStatusLabel,
  getPaymentMethodLabel,
  getDateRangeLabel,
  isSaleStatus,
  isReturnStatus,
  isRefundStatus,
  isInvoiceStatus,
  isReceiptStatus,
  getPaymentMethodsArray,
  getSaleStatusesArray,
  getReturnStatusesArray,
  getRefundStatusesArray,
  getInvoiceStatusesArray,
  getReceiptStatusesArray,
} from './constants';

// ============================================
// HELPERS - Export from helpers
// ============================================
export {
  generateId,
  generateReceiptNumber,
  generateInvoiceNumber,
  calculateTotal,
  calculateTax,
  calculateDiscount,
  // FIXED: Use the correct export names from helpers
  formatPhoneNumberHelper,
  truncateText,
  debounce,
  throttle,
  getStatusColorHelper,
  getPaymentMethodColorHelper,
  calculatePercentage,
  formatPercentageHelper,
  isEmpty as isEmptyHelper,
  deepClone,
  getInitials,
  getRandomColor,
  // Also export the helpers object
  helpers,
} from './helpers';

// ============================================
// NAVIGATION - Export from navigation
// ============================================
export {
  PUBLIC_ROUTES,
  ADMIN_ROUTES,
  API_ROUTES,
  publicNavItems,
  dashboardNavItems,
  salesNavItems,
  navigationGroups,
  isPublicRoute,
  isAdminRoute,
  getNavigationItems,
  getSalesNavItems,
  isRouteInNavGroup,
  getActiveNavItem,
  getBreadcrumbs,
} from './navigation';

// ============================================
// DEFAULT EXPORT
// ============================================
import { formatters } from './formatters';
import { constants } from './constants';
import { toast } from './toast-manager';
import { helpers } from './helpers';

export default {
  formatters,
  constants,
  toast,
  helpers,
};
