// D:\Projects\Kalwanga\packages\backend\src\controllers\paymentController.ts

import { Request, Response, NextFunction } from 'express';
import { paymentService } from '../services/paymentService.js';
import { mpesaService } from '../services/mpesaService.js';
import { AppError } from '../middleware/errorHandler.js';
import { z, ZodError } from 'zod';
import { logger } from '../lib/logger.js';
import Stripe from 'stripe';

// ============================================
// CONSTANTS
// ============================================

/**
 * Payment methods accepted by the API.
 *
 * `CRYPTO` and `CHECK` are preserved as reserved enum values —
 * accepted by the schema for forward compatibility, but no handler
 * is registered for them yet. Requests using either will fail with
 * a 400 "Unsupported payment method" from the service layer. This
 * is intentional: the schema documents the future surface, the
 * service enforces the current one.
 *
 * `PAYSTACK` was removed — no provider handler exists and the UI
 * no longer offers it. Do not re-add without also registering a
 * factory in `paymentService.initializeHandlers()`.
 *
 * `MTN`, `AIRTEL`, `TIGO`, `VODAFONE` are mobile-money
 * sub-providers. They are reachable directly when the caller knows
 * the exact network; normally they're routed via
 * `metadata.provider` on a `MOBILE_MONEY` request.
 */
const PAYMENT_METHODS = [
  'CASH',
  'CREDIT_CARD',
  'DEBIT_CARD',
  'MOBILE_MONEY',
  'BANK_TRANSFER',
  'GIFT_CARD',
  'LOYALTY_POINTS',
  'CRYPTO', // reserved — no handler registered
  'CHECK', // reserved — no handler registered
  'PAYPAL',
  'FLUTTERWAVE',
  'SQUARE',
  'MTN',
  'AIRTEL',
  'TIGO',
  'VODAFONE',
] as const;

const PAYMENT_STATUSES = [
  'PENDING',
  'PAID',
  'FAILED',
  'REFUNDED',
  'PARTIAL',
  'PROCESSING',
  'AUTHORIZED',
  'DECLINED',
] as const;

/**
 * Payment providers.
 *
 * `PAYSTACK` removed — see note on `PAYMENT_METHODS` above.
 */
const PAYMENT_PROVIDERS = [
  'STRIPE',
  'CASH',
  'MOBILE_MONEY',
  'BANK_TRANSFER',
  'GIFT_CARD',
  'LOYALTY_POINTS',
  'PAYPAL',
  'FLUTTERWAVE',
  'SQUARE',
  'MTN',
  'AIRTEL',
  'TIGO',
  'VODAFONE',
] as const;

const PAYMENT_PROVIDER_TYPES = ['ONLINE', 'OFFLINE', 'HYBRID'] as const;

/**
 * Known mobile-money networks. Used both by the Zod schema (to
 * validate `metadata.provider`) and by `routeMobileMoneyToNetwork`
 * (to rewrite `paymentMethod` before dispatch).
 */
const MOBILE_MONEY_NETWORKS = ['MTN', 'AIRTEL', 'TIGO', 'VODAFONE'] as const;

// ============================================
// VALIDATION SCHEMAS
// ============================================

/**
 * Loose phone-number shape check.
 *
 * Accepts digits, spaces, `+`, `(`, `)`, and `-`. Enforces an
 * absolute minimum of 10 digits (M-Pesa requires 12 including the
 * country code; the service layer applies the provider-specific
 * check). Rejects obviously malformed input like `"abcdefghij"`
 * before we ever hit the gateway.
 */
const PHONE_REGEX = /^[+\d][\d\s()-]{9,19}$/;

const processPaymentSchema = z
  .object({
    amount: z.number().positive('Amount must be positive'),
    paymentMethod: z.enum(PAYMENT_METHODS),
    saleId: z.string().optional(),
    orderId: z.string().optional(),
    cashRegisterId: z.string().optional(),
    cashRegisterSessionId: z.string().optional(),
    currency: z.string().optional(),
    source: z.string().optional(),
    customerId: z.string().optional(),
    metadata: z.record(z.any()).optional(),
    description: z.string().optional(),
    tipAmount: z.number().min(0).optional(),
    savePaymentMethod: z.boolean().optional(),
    businessUnitId: z.string().optional(),
    cardNonce: z.string().optional(),
    gatewayId: z.string().optional(),
    idempotencyKey: z.string().optional(),
  })
  .superRefine((data, ctx) => {
    // Square requires a card nonce generated by the Web SDK.
    if (data.paymentMethod === 'SQUARE' && !data.cardNonce) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        path: ['cardNonce'],
        message: 'cardNonce is required for SQUARE payments',
      });
    }

    // Cards need either a Stripe token (`source`) or a saved
    // PaymentMethod id (`gatewayId`).
    if (
      (data.paymentMethod === 'CREDIT_CARD' ||
        data.paymentMethod === 'DEBIT_CARD') &&
      !data.source &&
      !data.gatewayId
    ) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        path: ['source'],
        message:
          'source or gatewayId is required for card payments (Stripe token or saved payment method id)',
      });
    }

    // Gift cards require the code.
    if (data.paymentMethod === 'GIFT_CARD' && !data.gatewayId) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        path: ['gatewayId'],
        message: 'gatewayId (gift card code) is required for GIFT_CARD',
      });
    }

    // Generic MOBILE_MONEY requests must declare which network
    // they're on. Without this the service would fall back to the
    // simulator, which records a Payment without contacting any
    // real gateway.
    if (data.paymentMethod === 'MOBILE_MONEY') {
      const phone = (data.metadata as any)?.phoneNumber;
      const provider = String(
        (data.metadata as any)?.provider ?? '',
      ).toUpperCase();

      if (!phone) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,
          path: ['metadata.phoneNumber'],
          message:
            'metadata.phoneNumber is required for MOBILE_MONEY payments',
        });
      }

      if (!provider) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,
          path: ['metadata.provider'],
          message:
            'metadata.provider is required for MOBILE_MONEY (one of: MTN, AIRTEL, TIGO, VODAFONE)',
        });
      } else if (
        !(MOBILE_MONEY_NETWORKS as readonly string[]).includes(provider)
      ) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,
          path: ['metadata.provider'],
          message: `Unsupported mobile money provider "${provider}". Use MTN, AIRTEL, TIGO, or VODAFONE.`,
        });
      }
    }

    // Direct sub-provider requests also need a phone number.
    if (
      data.paymentMethod === 'MTN' ||
      data.paymentMethod === 'AIRTEL' ||
      data.paymentMethod === 'TIGO' ||
      data.paymentMethod === 'VODAFONE'
    ) {
      const phone = (data.metadata as any)?.phoneNumber;
      if (!phone) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,
          path: ['metadata.phoneNumber'],
          message: `metadata.phoneNumber is required for ${data.paymentMethod} payments`,
        });
      }
    }
  });

const refundSchema = z.object({
  amount: z.number().positive('Amount must be positive').optional(),
  reason: z.string().optional(),
});

const getPaymentsSchema = z.object({
  page: z.string().optional(),
  limit: z.string().optional(),
  startDate: z.string().optional(),
  endDate: z.string().optional(),
  businessUnitId: z.string().optional(),
  status: z.enum(PAYMENT_STATUSES).optional(),
  paymentMethod: z.enum(PAYMENT_METHODS).optional(),
  userId: z.string().optional(),
  saleId: z.string().optional(),
  orderId: z.string().optional(),
});

const checkoutSessionSchema = z.object({
  items: z
    .array(
      z.object({
        name: z.string().min(1, 'Item name is required'),
        price: z.number().positive('Price must be positive'),
        quantity: z.number().int().positive('Quantity must be positive'),
        currency: z.string().optional(),
        description: z.string().optional(),
        images: z.array(z.string()).optional(),
      }),
    )
    .min(1, 'At least one item is required'),
  customerId: z.string().optional(),
  successUrl: z.string().url().optional(),
  cancelUrl: z.string().url().optional(),
  metadata: z.record(z.any()).optional(),
});

const attachPaymentMethodSchema = z.object({
  paymentMethodId: z.string().min(1, 'Payment method ID is required'),
});

const createProviderSchema = z.object({
  provider: z.enum(PAYMENT_PROVIDERS),
  name: z.string().min(1, 'Provider name is required'),
  code: z.string().min(1, 'Provider code is required'),
  type: z.enum(PAYMENT_PROVIDER_TYPES),
  isActive: z.boolean().optional().default(true),
  isHealthy: z.boolean().optional().default(true),
  configured: z.boolean().optional().default(false),
  config: z.record(z.any()).optional(),
  businessUnitId: z.string().optional(),
  currencies: z.array(z.string()).optional().default([]),
  settings: z.record(z.any()).optional(),
  order: z.number().int().min(0).optional().default(0),
  paymentMethods: z
    .array(
      z.object({
        name: z.string().min(1),
        code: z.string().min(1),
        description: z.string().optional(),
        icon: z.string().optional(),
        isActive: z.boolean().optional().default(true),
        requiresRedirect: z.boolean().optional().default(false),
        isInstant: z.boolean().optional().default(true),
        minAmount: z.number().min(0).optional(),
        maxAmount: z.number().min(0).optional(),
        feePercentage: z.number().min(0).max(100).optional(),
        feeFixed: z.number().min(0).optional(),
        order: z.number().int().min(0).optional().default(0),
      }),
    )
    .optional()
    .default([]),
});

const updateProviderSchema = createProviderSchema.partial();

const configureProviderSchema = z.object({
  config: z.record(z.any()),
  settings: z.record(z.any()).optional(),
});

const updateProviderHealthSchema = z.object({
  isHealthy: z.boolean(),
});

/**
 * Stripe metadata must be a flat string→string map. Nested objects
 * are rejected by the Stripe API with a 400. Narrow the schema so
 * the rejection happens here, not at the network boundary.
 */
const createPaymentIntentSchema = z.object({
  amount: z.number().positive('Amount must be positive'),
  currency: z.string().default('USD'),
  description: z.string().optional(),
  metadata: z.record(z.string(), z.string()).optional(),
  customerId: z.string().optional(),
  idempotencyKey: z.string().optional(),
});

const mpesaSTKPushSchema = z.object({
  phoneNumber: z
    .string()
    .regex(PHONE_REGEX, 'Phone number format is invalid'),
  amount: z.number().positive('Amount must be positive'),
  accountReference: z.string().optional(),
  transactionDesc: z.string().optional(),
  callbackUrl: z.string().url().optional(),
  saleId: z.string().optional(),
  orderId: z.string().optional(),
  idempotencyKey: z.string().optional(),
  customerId: z.string().optional(),
  businessUnitId: z.string().optional(),
});

const mpesaB2CSchema = z.object({
  phoneNumber: z
    .string()
    .regex(PHONE_REGEX, 'Phone number format is invalid'),
  amount: z.number().positive('Amount must be positive'),
  commandId: z
    .enum(['BusinessPayment', 'SalaryPayment', 'PromotionPayment'])
    .default('BusinessPayment'),
  remarks: z.string().optional(),
  occasion: z.string().optional(),
});

const payPalCaptureSchema = z.object({
  orderId: z.string().min(1, 'Order ID is required'),
});

const flutterwaveVirtualAccountSchema = z.object({
  email: z.string().email('Valid email is required'),
  amount: z.number().positive('Amount must be positive').optional(),
  currency: z.string().optional(),
  customerName: z.string().optional(),
});

const squarePaymentSchema = z.object({
  amount: z.number().positive('Amount must be positive'),
  cardNonce: z.string().min(1, 'Card nonce is required'),
  currency: z.string().optional(),
  customerId: z.string().optional(),
  description: z.string().optional(),
  metadata: z.record(z.any()).optional(),
  saleId: z.string().optional(),
  orderId: z.string().optional(),
  businessUnitId: z.string().optional(),
  idempotencyKey: z.string().optional(),
});

const squareCustomerSchema = z.object({
  email: z.string().email('Valid email is required'),
  name: z.string().min(1, 'Name is required'),
  phone: z.string().optional(),
});

// ============================================
// HELPERS
// ============================================

function zodError(res: Response, error: z.ZodError) {
  return res.status(400).json({
    success: false,
    message: 'Validation error',
    errors: error.errors.map((e) => ({
      field: e.path.join('.'),
      message: e.message,
    })),
  });
}

/**
 * Extract the authenticated user's ID from the request.
 *
 * Supports both `req.user.id` and `req.user.userId` because
 * different auth middlewares populate one or the other.
 */
function requireUserId(req: Request): string {
  const userId = (req as any).user?.id ?? (req as any).user?.userId;
  if (!userId) {
    throw new AppError('User ID is required', 401);
  }
  return userId;
}

/**
 * Best-effort extraction of a sale id from any provider's webhook
 * payload. Returns the first non-empty value it finds.
 */
function extractSaleId(payload: any): string | null {
  if (!payload) return null;
  return (
    payload?.metadata?.saleId ||
    payload?.saleId ||
    payload?.data?.metadata?.saleId ||
    payload?.data?.saleId ||
    payload?.data?.meta?.saleId ||
    payload?.meta?.saleId ||
    payload?.resource?.custom_id ||
    payload?.resource?.purchase_units?.[0]?.custom_id ||
    payload?.data?.object?.payment?.metadata?.saleId ||
    null
  );
}

/**
 * Guard against the app misconfiguration where `express.json()`
 * parses the webhook body before it reaches us. Stripe, PayPal,
 * Paystack, and Square all need the raw Buffer for signature
 * verification.
 *
 * Returns `true` if the body is already a parsed object (wrong),
 * `false` if it's a Buffer (correct).
 */
function isParsedBody(body: unknown): boolean {
  return (
    body !== null &&
    typeof body === 'object' &&
    !Buffer.isBuffer(body)
  );
}

/**
 * Log a specific, actionable error when a signed webhook arrives
 * with a parsed body. The route must be mounted with
 * `express.raw({ type: 'application/json' })` *before* the global
 * `express.json()`, or the signature bytes are already lost.
 */
function warnIfParsedBody(provider: string, body: unknown): void {
  if (isParsedBody(body)) {
    logger.error(
      `[webhook:${provider}] req.body is a parsed object — signature verification will fail. ` +
        `Mount express.raw({ type: 'application/json' }) on the ${provider} webhook route ` +
        `BEFORE express.json().`,
    );
  }
}

/**
 * When a MOBILE_MONEY request carries `metadata.provider`, rewrite
 * the payment method to the concrete network (MTN, AIRTEL, TIGO,
 * VODAFONE) so the service routes to the real handler instead of
 * the simulator.
 *
 * If the caller passed a sub-provider directly (`paymentMethod:
 * 'MTN'`), this is a no-op.
 */
function routeMobileMoneyToNetwork<
  T extends { paymentMethod: string; metadata?: Record<string, any> },
>(input: T): T {
  if (input.paymentMethod !== 'MOBILE_MONEY') return input;

  const network = String(input.metadata?.provider ?? '').toUpperCase();
  if (!(MOBILE_MONEY_NETWORKS as readonly string[]).includes(network)) {
    return input;
  }

  return { ...input, paymentMethod: network };
}

// ============================================
// CONTROLLER
// ============================================

export const paymentController = {
  // ============================================
  // STRIPE / PAYMENT INTENT
  // ============================================

  async createPaymentIntent(req: Request, res: Response, next: NextFunction) {
    try {
      const validatedData = createPaymentIntentSchema.parse(req.body);
      const userId = requireUserId(req);

      const result = await paymentService.createPaymentIntent({
        ...validatedData,
        // Server-controlled userId is spread AFTER the caller's
        // metadata so it always wins, even if the client tries to
        // inject a `userId` key.
        metadata: {
          ...validatedData.metadata,
          userId,
        },
      });

      res.json({
        success: true,
        data: result,
        message: 'Payment intent created successfully',
      });
    } catch (error) {
      if (error instanceof ZodError) return zodError(res, error);
      next(error);
    }
  },

  // ============================================
  // M-PESA
  // ============================================

  async initiateMpesaSTKPush(req: Request, res: Response, next: NextFunction) {
    try {
      const validatedData = mpesaSTKPushSchema.parse(req.body);
      const userId = requireUserId(req);

      if (!mpesaService.isConfigured()) {
        throw new AppError(
          'M-Pesa is not configured. Please contact support.',
          503,
        );
      }

      const result = await mpesaService.initiateSTKPush({
        phoneNumber: validatedData.phoneNumber,
        amount: validatedData.amount,
        accountReference:
          validatedData.accountReference || `PAY-${Date.now()}`,
        transactionDesc:
          validatedData.transactionDesc || 'Payment via M-Pesa',
        callbackUrl: validatedData.callbackUrl,
      });

      const payment = await paymentService.createPendingPayment({
        amount: validatedData.amount,
        paymentMethod: 'MOBILE_MONEY',
        userId,
        saleId: validatedData.saleId,
        orderId: validatedData.orderId,
        transactionId: result.CheckoutRequestID,
        reference: result.MerchantRequestID,
        idempotencyKey: validatedData.idempotencyKey,
        metadata: {
          checkoutRequestId: result.CheckoutRequestID,
          merchantRequestId: result.MerchantRequestID,
          phoneNumber: validatedData.phoneNumber,
          provider: 'MPESA',
          idempotencyKey: validatedData.idempotencyKey ?? null,
          customerId: validatedData.customerId ?? null,
          businessUnitId: validatedData.businessUnitId ?? null,
        },
      });

      res.json({
        success: true,
        data: { ...result, paymentId: payment.id },
        message: 'M-Pesa STK Push initiated successfully',
      });
    } catch (error) {
      if (error instanceof ZodError) return zodError(res, error);
      next(error);
    }
  },

  /**
   * Query the status of an M-Pesa transaction.
   *
   * `req.params.transactionId` MUST be the CheckoutRequestID that
   * was returned by `initiateMpesaSTKPush` and stored on the local
   * `Payment.transactionId` column. Passing the MerchantRequestID
   * will query a nonexistent transaction on Safaricom's side and
   * resolve to no local Payment.
   *
   * As a safety net, if the primary lookup misses we also try the
   * `reference` column, since some callers record the
   * MerchantRequestID there.
   */
  async queryMpesaStatus(req: Request, res: Response, next: NextFunction) {
    try {
      const { transactionId } = req.params;

      if (!transactionId) {
        throw new AppError('Transaction ID is required', 400);
      }

      const result = await mpesaService.queryTransactionStatus({
        transactionId,
        shortcode: process.env.MPESA_SHORTCODE || '174379',
      });

      // Primary lookup: Payment.transactionId === CheckoutRequestID.
      let payment = await paymentService.getPaymentByTransactionId(
        transactionId,
      );

      // Fallback: some flows store the MerchantRequestID in
      // Payment.reference. Try that before giving up.
      if (!payment) {
        const { prisma } = await import('../lib/prisma.js');
        payment = await prisma.payment.findFirst({
          where: {
            OR: [{ transactionId }, { reference: transactionId }],
          },
          include: { sale: true, order: true, user: true },
        });
      }

      if (payment && result.ResultCode !== undefined) {
        const status = result.ResultCode === '0' ? 'PAID' : 'FAILED';

        if (payment.status !== status) {
          await paymentService.updatePaymentStatus(payment.id, status, {
            notes: `M-Pesa status: ${result.ResultDesc || 'Status updated'}`,
            metadata: {
              ...((payment.metadata as any) ?? {}),
              mpesaResult: result,
            },
          });

          const saleId =
            payment.saleId || extractSaleId(payment.metadata);
          if (saleId) {
            if (status === 'PAID') {
              await paymentService.completeCheckoutFromGateway(
                saleId,
                payment.id,
                result,
                'MPESA',
              );
            } else {
              await paymentService.failCheckoutFromGateway(
                saleId,
                payment.id,
                result,
                'MPESA',
                result.ResultDesc || 'M-Pesa status query failed',
              );
            }
          } else if (status === 'PAID' && payment.orderId) {
            await paymentService.updateOrderAfterPayment(
              payment.orderId,
              payment.amount,
              payment,
            );
          }
        }
      }

      res.json({
        success: true,
        data: result,
        payment,
        message: 'Transaction status retrieved successfully',
      });
    } catch (error) {
      next(error);
    }
  },

  /**
   * M-Pesa STK push callback.
   *
   * Safaricom posts here when the customer enters their PIN (or the
   * request times out). This is the ONLY place the Sale can flip
   * from PENDING → COMPLETED for M-Pesa.
   *
   * Idempotency: Safaricom retries aggressively. We look the Payment
   * row up by `CheckoutRequestID` and short-circuit if it's already
   * in a terminal state.
   *
   * ⚠ On internal errors we still return 200 so Safaricom doesn't
   *   hammer us. Reconciliation is handled by an out-of-band job
   *   that queries `mpesaService.queryTransactionStatus` for any
   *   PENDING payment older than N minutes.
   */
  async handleMpesaCallback(req: Request, res: Response, next: NextFunction) {
    try {
      logger.info('M-Pesa callback received:', JSON.stringify(req.body));

      const result = await mpesaService.handleSTKPushCallback(req.body);

      // Look up the payment by CheckoutRequestID first, falling
      // back to `reference` (MerchantRequestID) so that a callback
      // is never dropped just because the caller stored a different
      // id shape.
      let payment = await paymentService.getPaymentByTransactionId(
        result.checkoutRequestId,
      );

      if (!payment) {
        const { prisma } = await import('../lib/prisma.js');
        payment = await prisma.payment.findFirst({
          where: {
            OR: [
              { transactionId: result.checkoutRequestId },
              { reference: result.checkoutRequestId },
            ],
          },
          include: { sale: true, order: true, user: true },
        });
      }

      if (payment) {
        // Short-circuit if we've already handled this callback.
        if (payment.status === 'PAID' || payment.status === 'FAILED') {
          logger.info(
            `[webhook:MPESA] Payment ${payment.id} already ${payment.status} — idempotent skip`,
          );
          return res
            .status(200)
            .json({ ResultCode: 0, ResultDesc: 'Success' });
        }

        if (result.isSuccess) {
          await paymentService.updatePaymentStatus(payment.id, 'PAID', {
            metadata: {
              ...((payment.metadata as any) ?? {}),
              mpesaCallback: result.callbackMetadata,
              resultCode: result.resultCode,
              resultDesc: result.resultDesc,
            },
            notes: `M-Pesa payment successful: ${result.resultDesc}`,
          });

          const saleId =
            payment.saleId || extractSaleId(payment.metadata);
          if (saleId) {
            await paymentService.completeCheckoutFromGateway(
              saleId,
              payment.id,
              result.callbackMetadata ?? result,
              'MPESA',
            );
          } else if (payment.orderId) {
            await paymentService.updateOrderAfterPayment(
              payment.orderId,
              payment.amount,
              payment,
            );
          }

          await paymentService.createPaymentNotification(
            payment,
            'succeeded',
          );
        } else {
          await paymentService.updatePaymentStatus(payment.id, 'FAILED', {
            notes: `M-Pesa payment failed: ${result.resultDesc}`,
            metadata: {
              ...((payment.metadata as any) ?? {}),
              mpesaCallback: result,
              resultCode: result.resultCode,
              resultDesc: result.resultDesc,
            },
          });

          const saleId =
            payment.saleId || extractSaleId(payment.metadata);
          if (saleId) {
            await paymentService.failCheckoutFromGateway(
              saleId,
              payment.id,
              result,
              'MPESA',
              result.resultDesc || 'M-Pesa payment failed',
            );
          }

          await paymentService.createPaymentNotification(
            payment,
            'failed',
          );
        }
      } else {
        logger.warn(
          `[webhook:MPESA] No payment found for CheckoutRequestID ${result.checkoutRequestId}`,
        );
      }

      // Always return 200 to Safaricom — they retry on non-2xx.
      res.status(200).json({ ResultCode: 0, ResultDesc: 'Success' });
    } catch (error) {
      logger.error('Callback processing error:', error);
      res.status(200).json({ ResultCode: 0, ResultDesc: 'Success' });
    }
  },

  async processMpesaB2C(req: Request, res: Response, next: NextFunction) {
    try {
      const validatedData = mpesaB2CSchema.parse(req.body);
      requireUserId(req);

      if (!mpesaService.isConfigured()) {
        throw new AppError(
          'M-Pesa is not configured. Please contact support.',
          503,
        );
      }

      const result = await mpesaService.processB2CPayment({
        phoneNumber: validatedData.phoneNumber,
        amount: validatedData.amount,
        commandId: validatedData.commandId,
        remarks: validatedData.remarks || 'Payment from POS',
        occasion: validatedData.occasion,
      });

      res.json({
        success: true,
        data: result,
        message: 'M-Pesa B2C payment initiated successfully',
      });
    } catch (error) {
      if (error instanceof ZodError) return zodError(res, error);
      next(error);
    }
  },

  // ============================================
  // PAYPAL
  // ============================================

  async capturePayPalOrder(req: Request, res: Response, next: NextFunction) {
    try {
      const { orderId } = payPalCaptureSchema.parse(req.body);

      const result = await paymentService.capturePayPalOrder(orderId);

      res.json({
        success: true,
        data: result,
        message: 'PayPal order captured successfully',
      });
    } catch (error) {
      if (error instanceof ZodError) return zodError(res, error);
      next(error);
    }
  },

  async handlePayPalWebhook(req: Request, res: Response, next: NextFunction) {
    try {
      warnIfParsedBody('PAYPAL', req.body);

      const result = await paymentService.handlePayPalWebhook(
        req.body,
        req.headers as Record<string, string>,
      );

      res.json({ success: true, ...result });
    } catch (error) {
      logger.error('PayPal webhook error:', error);
      // Always 200 so PayPal doesn't retry forever.
      res.status(200).json({ success: true });
    }
  },

  // ============================================
  // FLUTTERWAVE
  // ============================================

  async createFlutterwaveVirtualAccount(
    req: Request,
    res: Response,
    next: NextFunction,
  ) {
    try {
      const validatedData = flutterwaveVirtualAccountSchema.parse(req.body);

      const result = await paymentService.createFlutterwaveVirtualAccount({
        email: validatedData.email,
        amount: validatedData.amount,
        currency: validatedData.currency,
        customerName: validatedData.customerName,
      });

      res.json({
        success: true,
        data: result,
        message: 'Virtual account created successfully',
      });
    } catch (error) {
      if (error instanceof ZodError) return zodError(res, error);
      next(error);
    }
  },

  async handleFlutterwaveWebhook(
    req: Request,
    res: Response,
    next: NextFunction,
  ) {
    try {
      warnIfParsedBody('FLUTTERWAVE', req.body);

      const signature = (req.headers['verif-hash'] as string) || '';

      // Flutterwave's signature is a plain-string equality check
      // against the secret hash — it doesn't sign the body. We still
      // forward the raw body so the service API remains uniform and
      // future-proof.
      const rawBody = Buffer.isBuffer(req.body)
        ? req.body
        : Buffer.from(JSON.stringify(req.body ?? {}));

      // Parse to an object for the switch-on-event logic. The
      // service will re-verify against the raw bytes.
      const payload = Buffer.isBuffer(req.body)
        ? JSON.parse(req.body.toString('utf8'))
        : req.body;

      const result = await paymentService.handleFlutterwaveWebhook(
        payload,
        signature,
        rawBody,
      );

      res.json({ success: true, ...result });
    } catch (error) {
      logger.error('Flutterwave webhook error:', error);
      // Always 200 — Flutterwave retries on non-2xx.
      res.status(200).json({ success: true });
    }
  },

  // ============================================
  // SQUARE
  // ============================================

  async processSquarePayment(req: Request, res: Response, next: NextFunction) {
    try {
      const validatedData = squarePaymentSchema.parse(req.body);
      const userId = requireUserId(req);

      const payment = await paymentService.processPayment({
        amount: validatedData.amount,
        paymentMethod: 'SQUARE',
        userId,
        currency: validatedData.currency || 'USD',
        cardNonce: validatedData.cardNonce,
        customerId: validatedData.customerId,
        description: validatedData.description,
        idempotencyKey: validatedData.idempotencyKey,
        // Pass the sale/order linkage through BOTH at the top level
        // and in metadata so the Square webhook can find the Sale
        // regardless of which path its reader walks.
        saleId: validatedData.saleId,
        orderId: validatedData.orderId,
        businessUnitId: validatedData.businessUnitId,
        metadata: {
          ...(validatedData.metadata ?? {}),
          saleId: validatedData.saleId ?? null,
          orderId: validatedData.orderId ?? null,
        },
      });

      res.json({
        success: true,
        data: payment,
        message: 'Square payment processed successfully',
      });
    } catch (error) {
      if (error instanceof ZodError) return zodError(res, error);
      next(error);
    }
  },

  async createSquareCustomer(req: Request, res: Response, next: NextFunction) {
    try {
      const validatedData = squareCustomerSchema.parse(req.body);

      const result = await paymentService.createSquareCustomer({
        email: validatedData.email,
        name: validatedData.name,
        phone: validatedData.phone,
      });

      res.json({
        success: true,
        data: result,
        message: 'Square customer created successfully',
      });
    } catch (error) {
      if (error instanceof ZodError) return zodError(res, error);
      next(error);
    }
  },

  async handleSquareWebhook(req: Request, res: Response, next: NextFunction) {
    try {
      warnIfParsedBody('SQUARE', req.body);

      const signature =
        (req.headers['x-square-hmacsha256-signature'] as string) || '';

      // Square signs `notificationUrl + rawBody`. The notification
      // URL must be the exact one Square is configured with.
      const rawBody = Buffer.isBuffer(req.body)
        ? req.body
        : Buffer.from(JSON.stringify(req.body ?? {}));

      const payload = Buffer.isBuffer(req.body)
        ? JSON.parse(req.body.toString('utf8'))
        : req.body;

      const result = await paymentService.handleSquareWebhook(
        payload,
        signature,
        rawBody,
        process.env.SQUARE_WEBHOOK_URL,
      );

      res.json({ success: true, ...result });
    } catch (error) {
      logger.error('Square webhook error:', error);
      // Always 200 — Square retries on non-2xx.
      res.status(200).send('OK');
    }
  },

  // ============================================
  // PAYMENT PROVIDER MANAGEMENT
  // ============================================

  async getPaymentProviders(req: Request, res: Response, next: NextFunction) {
    try {
      const userId = (req as any).user?.id ?? (req as any).user?.userId;
      const businessUnitId =
        (req.query.businessUnitId as string) ||
        (req as any).user?.businessUnitId;

      const providers = await paymentService.getPaymentProviders(
        userId,
        businessUnitId,
      );

      res.json({
        success: true,
        data: providers,
        message: 'Payment providers retrieved successfully',
      });
    } catch (error) {
      next(error);
    }
  },

  async getProviderStatus(req: Request, res: Response, next: NextFunction) {
    try {
      const { provider } = req.params;
      const businessUnitId =
        (req.query.businessUnitId as string) ||
        (req as any).user?.businessUnitId;

      const status = await paymentService.getProviderStatus(
        provider,
        businessUnitId,
      );

      res.json({
        success: true,
        data: status,
        message: 'Provider status retrieved successfully',
      });
    } catch (error) {
      next(error);
    }
  },

  async createProvider(req: Request, res: Response, next: NextFunction) {
    try {
      const validatedData = createProviderSchema.parse(req.body);
      const userId = requireUserId(req);

      if (validatedData.provider === 'STRIPE') {
        const apiKey =
          (validatedData.config?.apiKey as string) ||
          process.env.STRIPE_SECRET_KEY;
        if (!apiKey) {
          throw new AppError('Stripe API key is required', 400);
        }
        try {
          const stripe = new Stripe(apiKey, { apiVersion: '2023-10-16' });
          await stripe.balance.retrieve();
        } catch {
          throw new AppError('Invalid Stripe API key', 400);
        }
      }

      if (validatedData.provider === 'MOBILE_MONEY') {
        if (!mpesaService.isConfigured()) {
          throw new AppError(
            'M-Pesa is not configured. Please set MPESA_CONSUMER_KEY and MPESA_CONSUMER_SECRET.',
            400,
          );
        }
      }

      if (validatedData.provider === 'PAYPAL') {
        const clientId =
          (validatedData.config?.clientId as string) ||
          process.env.PAYPAL_CLIENT_ID;
        const clientSecret =
          (validatedData.config?.clientSecret as string) ||
          process.env.PAYPAL_CLIENT_SECRET;
        if (!clientId || !clientSecret) {
          throw new AppError(
            'PayPal Client ID and Client Secret are required',
            400,
          );
        }
      }

      if (validatedData.provider === 'FLUTTERWAVE') {
        const apiKey =
          (validatedData.config?.apiKey as string) ||
          process.env.FLUTTERWAVE_API_KEY;
        const publicKey =
          (validatedData.config?.publicKey as string) ||
          process.env.FLUTTERWAVE_PUBLIC_KEY;
        if (!apiKey || !publicKey) {
          throw new AppError(
            'Flutterwave API Key and Public Key are required',
            400,
          );
        }
      }

      if (validatedData.provider === 'SQUARE') {
        const accessToken =
          (validatedData.config?.accessToken as string) ||
          process.env.SQUARE_ACCESS_TOKEN;
        const locationId =
          (validatedData.config?.locationId as string) ||
          process.env.SQUARE_LOCATION_ID;
        if (!accessToken || !locationId) {
          throw new AppError(
            'Square Access Token and Location ID are required',
            400,
          );
        }
      }

      const provider = await paymentService.createPaymentProvider(
        validatedData,
        userId,
      );

      res.status(201).json({
        success: true,
        data: provider,
        message: 'Payment provider created successfully',
      });
    } catch (error) {
      if (error instanceof ZodError) return zodError(res, error);
      next(error);
    }
  },

  async updateProvider(req: Request, res: Response, next: NextFunction) {
    try {
      const { id } = req.params;
      const validatedData = updateProviderSchema.parse(req.body);
      const userId = requireUserId(req);

      const provider = await paymentService.updatePaymentProvider(
        id,
        validatedData,
        userId,
      );

      res.json({
        success: true,
        data: provider,
        message: 'Payment provider updated successfully',
      });
    } catch (error) {
      if (error instanceof ZodError) return zodError(res, error);
      next(error);
    }
  },

  async deleteProvider(req: Request, res: Response, next: NextFunction) {
    try {
      const { id } = req.params;
      const userId = requireUserId(req);

      await paymentService.deletePaymentProvider(id, userId);

      res.json({
        success: true,
        message: 'Payment provider deleted successfully',
      });
    } catch (error) {
      next(error);
    }
  },

  async updateProviderHealth(req: Request, res: Response, next: NextFunction) {
    try {
      const { id } = req.params;
      const { isHealthy } = updateProviderHealthSchema.parse(req.body);
      const userId = requireUserId(req);

      const provider = await paymentService.updateProviderHealthWithAudit(
        id,
        isHealthy,
        userId,
      );

      res.json({
        success: true,
        data: provider,
        message: 'Provider health updated successfully',
      });
    } catch (error) {
      if (error instanceof ZodError) return zodError(res, error);
      next(error);
    }
  },

  async configureProvider(req: Request, res: Response, next: NextFunction) {
    try {
      const { id } = req.params;
      const { config, settings } = configureProviderSchema.parse(req.body);
      const userId = requireUserId(req);

      const provider = await paymentService.getProviderById(id);
      if (!provider) {
        throw new AppError('Provider not found', 404);
      }

      if (provider.provider === 'STRIPE' && config?.apiKey) {
        try {
          const stripe = new Stripe(config.apiKey as string, {
            apiVersion: '2023-10-16',
          });
          await stripe.balance.retrieve();
        } catch {
          throw new AppError('Invalid Stripe API key', 400);
        }
      }

      if (provider.provider === 'MOBILE_MONEY') {
        if (!mpesaService.isConfigured()) {
          throw new AppError(
            'M-Pesa is not configured. Please set MPESA_CONSUMER_KEY and MPESA_CONSUMER_SECRET.',
            400,
          );
        }
      }

      if (provider.provider === 'PAYPAL') {
        if (!config?.clientId || !config?.clientSecret) {
          throw new AppError(
            'PayPal Client ID and Client Secret are required',
            400,
          );
        }
      }

      if (provider.provider === 'FLUTTERWAVE') {
        if (!config?.apiKey || !config?.publicKey) {
          throw new AppError(
            'Flutterwave API Key and Public Key are required',
            400,
          );
        }
      }

      if (provider.provider === 'SQUARE') {
        if (!config?.accessToken || !config?.locationId) {
          throw new AppError(
            'Square Access Token and Location ID are required',
            400,
          );
        }
      }

      const updatedProvider = await paymentService.configureProvider(
        id,
        config,
        settings,
        userId,
      );

      res.json({
        success: true,
        data: updatedProvider,
        message: 'Provider configured successfully',
      });
    } catch (error) {
      if (error instanceof ZodError) return zodError(res, error);
      next(error);
    }
  },

  async addProviderCurrency(req: Request, res: Response, next: NextFunction) {
    try {
      const { id } = req.params;
      const { currency, conversionRate } = req.body;
      const userId = requireUserId(req);

      if (!currency) {
        throw new AppError('Currency is required', 400);
      }

      const result = await paymentService.addProviderCurrency(
        id,
        currency,
        conversionRate,
        userId,
      );

      res.json({
        success: true,
        data: result,
        message: 'Currency added successfully',
      });
    } catch (error) {
      next(error);
    }
  },

  async removeProviderCurrency(
    req: Request,
    res: Response,
    next: NextFunction,
  ) {
    try {
      const { id, currency } = req.params;
      const userId = requireUserId(req);

      if (!currency) {
        throw new AppError('Currency is required', 400);
      }

      await paymentService.removeProviderCurrency(id, currency, userId);

      res.json({
        success: true,
        message: 'Currency removed successfully',
      });
    } catch (error) {
      next(error);
    }
  },

  // ============================================
  // CORE PAYMENT ENDPOINTS
  // ============================================

  async processPayment(req: Request, res: Response, next: NextFunction) {
    try {
      const validatedData = processPaymentSchema.parse(req.body);
      const userId = requireUserId(req);

      // Route MOBILE_MONEY to the concrete network so the service
      // dispatches to MTN/AIRTEL/TIGO/VODAFONE handlers instead of
      // the simulator. A no-op for every other method.
      const routed = routeMobileMoneyToNetwork(validatedData);

      const payment = await paymentService.processPayment({
        ...routed,
        userId,
      });

      res.status(201).json({
        success: true,
        data: payment,
        message: 'Payment processed successfully',
      });
    } catch (error) {
      if (error instanceof ZodError) return zodError(res, error);
      next(error);
    }
  },

  async refundPayment(req: Request, res: Response, next: NextFunction) {
    try {
      const { id } = req.params;
      const { amount, reason } = refundSchema.parse(req.body);
      const userId =
        (req as any).user?.id ?? (req as any).user?.userId;

      if (!id) {
        throw new AppError('Payment ID is required', 400);
      }

      const result = await paymentService.refundPayment(
        id,
        amount,
        reason,
        userId,
      );

      res.json({
        success: true,
        data: result,
        message: 'Payment refunded successfully',
      });
    } catch (error) {
      if (error instanceof ZodError) return zodError(res, error);
      next(error);
    }
  },

  async getPaymentStatus(req: Request, res: Response, next: NextFunction) {
    try {
      const { id } = req.params;

      if (!id) {
        throw new AppError('Payment ID is required', 400);
      }

      const payment = await paymentService.getPaymentStatus(id);

      res.json({ success: true, data: payment });
    } catch (error) {
      next(error);
    }
  },

  /**
   * Get aggregate payment statistics.
   *
   * Errors propagate to the error middleware; a successful query
   * that genuinely has no rows returns zeros with a 200.
   */
  async getPaymentSummary(req: Request, res: Response, next: NextFunction) {
    try {
      const { startDate, endDate, businessUnitId, status, paymentMethod } =
        req.query;
      requireUserId(req);

      const summary = await paymentService.getPaymentSummary({
        startDate: startDate ? new Date(startDate as string) : undefined,
        endDate: endDate ? new Date(endDate as string) : undefined,
        businessUnitId: businessUnitId as string | undefined,
        status: status as any,
        paymentMethod: paymentMethod as any,
      });

      if (!summary) {
        return res.json({
          success: true,
          data: {
            totalAmount: 0,
            byMethod: {},
            count: 0,
            averageAmount: 0,
            totalRefunds: 0,
            refundCount: 0,
            netAmount: 0,
          },
          message: 'No payment data available',
        });
      }

      res.json({
        success: true,
        data: summary,
        message: 'Payment summary retrieved successfully',
      });
    } catch (error) {
      next(error);
    }
  },

  async getAllPayments(req: Request, res: Response, next: NextFunction) {
    try {
      const validatedQuery = getPaymentsSchema.parse(req.query);

      const {
        page,
        limit,
        startDate,
        endDate,
        businessUnitId,
        status,
        paymentMethod,
        userId,
        saleId,
        orderId,
      } = validatedQuery;

      const result = await paymentService.getAllPayments({
        page: page ? parseInt(page) : 1,
        limit: limit ? parseInt(limit) : 20,
        startDate: startDate ? new Date(startDate) : undefined,
        endDate: endDate ? new Date(endDate) : undefined,
        businessUnitId: businessUnitId as string | undefined,
        status: status as any,
        paymentMethod: paymentMethod as any,
        userId: userId as string | undefined,
        saleId: saleId as string | undefined,
        orderId: orderId as string | undefined,
      });

      res.json({
        success: true,
        data: result.payments,
        pagination: {
          total: result.total,
          page: result.page,
          totalPages: result.totalPages,
          limit: result.limit,
        },
      });
    } catch (error) {
      if (error instanceof ZodError) return zodError(res, error);
      next(error);
    }
  },

  // ============================================
  // STRIPE CHECKOUT & CUSTOMER
  // ============================================

  async createCheckoutSession(req: Request, res: Response, next: NextFunction) {
    try {
      const validatedData = checkoutSessionSchema.parse(req.body);
      const { items, customerId, successUrl, cancelUrl, metadata } =
        validatedData;

      const session = await paymentService.createCheckoutSession(
        items,
        customerId,
        successUrl,
        cancelUrl,
        metadata,
      );

      res.json({
        success: true,
        data: session,
        message: 'Checkout session created',
      });
    } catch (error) {
      if (error instanceof ZodError) return zodError(res, error);
      next(error);
    }
  },

  /**
   * Stripe webhook handler.
   *
   * ⚠ Requires the RAW request body. If `req.body` arrives as a
   *   parsed object, `stripe.webhooks.constructEvent` throws
   *   "Webhook signature verification failed" on every request.
   *
   * When that misconfiguration is detected we ACK with a 200 —
   * returning 5xx would make Stripe retry every event for up to
   * 72 hours, and the route is still misconfigured, so every retry
   * would fail identically. The correct recovery is: log loudly,
   * fix the mount order, and reconcile any missed events
   * out-of-band by querying Stripe for the affected window.
   */
  async handleWebhook(req: Request, res: Response, next: NextFunction) {
    try {
      const signature = req.headers['stripe-signature'] as string;

      if (!signature) {
        // Missing header is a real client error, not a
        // misconfiguration — Stripe always sends it. A 400 here
        // is appropriate and Stripe will not retry a 4xx.
        throw new AppError('Stripe signature is required', 400);
      }

      if (isParsedBody(req.body)) {
        logger.error(
          '[webhook:STRIPE] req.body is a parsed object — Stripe signature verification will fail. ' +
            'Mount express.raw({ type: "application/json" }) on /api/payments/webhook BEFORE express.json(). ' +
            'ACKing the event so Stripe does not retry; reconcile the affected window out-of-band.',
        );
        return res.status(200).json({
          success: true,
          received: true,
          processed: false,
          reason: 'route-misconfigured',
        });
      }

      const result = await paymentService.handleWebhook(req.body, signature);

      return res.json({ success: true, ...result });
    } catch (error) {
      // A 400 from the AppError above is a real client error and
      // should propagate. Everything else — including signature
      // verification failures — gets ACKed so Stripe stops retrying.
      if (error instanceof AppError && (error as any).statusCode === 400) {
        return next(error);
      }

      logger.error('Webhook error:', error);
      return res.status(200).json({
        success: true,
        received: true,
        processed: false,
      });
    }
  },

  async createStripeCustomer(req: Request, res: Response, next: NextFunction) {
    try {
      const userId = requireUserId(req);

      const result = await paymentService.createStripeCustomer(userId);

      res.json({
        success: true,
        data: result,
        message: result.alreadyExists
          ? 'Customer already exists'
          : 'Customer created',
      });
    } catch (error) {
      next(error);
    }
  },

  async getPaymentMethods(req: Request, res: Response, next: NextFunction) {
    try {
      const userId = requireUserId(req);

      const paymentMethods = await paymentService.getCustomerPaymentMethods(
        userId,
      );

      res.json({ success: true, data: paymentMethods });
    } catch (error) {
      next(error);
    }
  },

  async attachPaymentMethod(req: Request, res: Response, next: NextFunction) {
    try {
      const userId = requireUserId(req);
      const { paymentMethodId } = attachPaymentMethodSchema.parse(req.body);

      const paymentMethod = await paymentService.attachPaymentMethod(
        userId,
        paymentMethodId,
      );

      res.json({
        success: true,
        data: paymentMethod,
        message: 'Payment method attached',
      });
    } catch (error) {
      if (error instanceof ZodError) return zodError(res, error);
      next(error);
    }
  },

  async detachPaymentMethod(req: Request, res: Response, next: NextFunction) {
    try {
      const { id } = req.params;

      if (!id) {
        throw new AppError('Payment method ID is required', 400);
      }

      const result = await paymentService.detachPaymentMethod(id);

      res.json({
        success: true,
        data: result,
        message: 'Payment method detached',
      });
    } catch (error) {
      next(error);
    }
  },
};

export default paymentController;
